---
title: "Talks + Pubs — Complete list"
description: |
  Complete list of talks and publications
---

# Talks

[Openscapes: Better Science for Future Us. Supporting NASA Earth science research teams’ migration to the cloud](https://docs.google.com/presentation/d/1SVwkEDe2gUzJJZ5NGsGTsGPde-NJm9HLtKieSeuthfI/edit?usp=sharing) - August 12, 2021: LP DAAC User Working Group (20 minutes)

[Better Science for Future Us](https://docs.google.com/presentation/d/1HGw4P095-lblHiGQHXYidHiVysjrPxuojxTxKtE13vk/edit?usp=sharing) — July 12, 2021: Plenary at the inaugural Society for Open, Reliable, and Transparent Ecology and Evolutionary Biology [SORTEE conference](https://www.sortee.org/events/) (30 minutes) ([video](https://osf.io/47req/))

[Better Science for Future Us](https://docs.google.com/presentation/d/17XcJSxoE3_-0PqYgQ0l7NctniBNUxaZ5Zo0hjL-bjJo/edit?usp=sharing) - June 30, 2021: [PANGEO Showcase](https://pangeo.io/pangeo-showcase.html) (15 minutes) ([PANGEO Discourse](https://discourse.pangeo.io/t/june-30-2021-the-nasa-openscapes-framework/1631), [Zenodo](https://zenodo.org/record/5090115#.YO3kom5lDUI))

[Open science as a movement and the art of Openscapes](https://docs.google.com/presentation/d/11-flAlM33E7GwkzlJuuzbs8icfTgYnG7UmDwDkgD49k/edit?usp=sharing) — June 5, 2021: Keynote with Dr. Allison Horst at [CascadiaR Conference](https://cascadiarconf.com/) (20 minutes) 

[Learning to code with open science communities](https://docs.google.com/presentation/d/1hnK6AdZpKeKILph8rBJoXXT2QKyYgvNlhqsoZ3PQ46s/edit?usp=sharing) — June 4, 2021: [*Nature* Webcast](https://www.nature.com/webcasts/event/how-to-start-learning-to-code-in-research/) ([video](https://www.nature.com/articles/d41586-021-01638-z)) (10 minutes)
<!---https://docs.google.com/presentation/d/1hnK6AdZpKeKILph8rBJoXXT2QKyYgvNlhqsoZ3PQ46s/edit#slide=id.gd8d3954c7d_0_319--->

[Openscapes for better science in less time, together](https://docs.google.com/presentation/d/1Mc__4NfMlLHvChoAWnvEqUocP8JS9Ya317hHRaZhLnM/edit?usp=sharing) — April 6, 2021: CZI Seed Networks Computational Biology Meeting (30 minutes)

[NASA DAACs Openscapes Framework](https://docs.google.com/presentation/d/1_2ybhWlbg_Y_NrTQ_FF8JqqmbsstCkt5IKZqHmwDtFg/edit?usp=sharing) — March 25, 2021: NASA ESDS-ESDIS-DAACs-IMPACT Meeting (15 minutes)

[How you can do better science in less time](https://docs.google.com/presentation/d/1EGSTC-p0kKCV3TNpc65Kyy1S0OOFmDalO917S0UIRvE/edit?usp=sharing) — March 5, 2021: University of South Florida – College of Marine Science Seminar Series with Dr. Marcus Beck: [Open science lessons from Tampa Bay ](https://www.canva.com/design/DAEXu-oE6M4/o4okxvLdSs6t3lrxfqApkA/edit#1) (20 minutes each) ([video](https://www.youtube.com/watch?v=21qS05Yv3GQ&t=195s))

<!---https://twitter.com/colorsofscience/status/1367957167295373315--->

[Open practices for better science in less time](https://openscapes.github.io/slides/betterscience/environment-canada#1) — February 24, 2021: Open Science Community of Practice, Environment and Climate Change Canada (40 minutes) ([video](https://youtu.be/F1Df1Macz0g))

[NASA DAACs Openscapes Framework](https://docs.google.com/presentation/d/11zgFIzYaMMsNTQVpUY5z3GnPUqTKQLJFTUsF4gi3qQ4/edit?usp=sharing) — February 10, 2021: NASA's Earth Science Data System Working Groups (ESDSWG) (5 minutes)

[Openscapes](https://docs.google.com/presentation/d/1ty--0Jr7HRD3VXro5K8eMPaxApzeE1dkAZKVC4jyxm0/edit?usp=sharing) — December 16, 2020 Invest in Open's [Joint Roadmap for Open Science Tools (JROST) Conference](https://investinopen.org/community/jrost-2020-conference/) (5 minutes)


[**Audience building for open source projects** - Workshop at Chan Zuckerberg Initiative Essential Open Source Software for Science Meeting - December 8, 2020](https://docs.google.com/presentation/d/1n4Z87Z8ax_pUUO98lHzsOGYHTtbshr_LB5JSznOiIW0/edit?usp=sharing)

[**Normalizing talking about data** - CSCCE Data Science Special Interest Group Discussion - November 23, 2020](https://docs.google.com/presentation/d/15FsK37GQVvhL9zbnP1E1n9CEn-Xu5HvIe2FaIMpdC0s/edit?usp=sharing)

[**R and teamwork for better science in less time** - ](https://openscapes.github.io/slides/betterscience/nwfsc#1) [NOAA Northwest Fisheries Science Center - November 19, 2020](https://www.fisheries.noaa.gov/event/nwfsc-monster-seminar-jam-julia-stewart-lowndes)

[**How to empower researchers with open science through meeting analytical needs and supporting people**](https://docs.google.com/presentation/d/1AmnPV8eLQl9_0EuHQAqp7xBMHcUlcFkM30509BwJkMA/edit?usp=sharing) [- National Academies of Sciences, Engineering, and Medicine (NASEM) Roundtable on Aligning Incentives for Open Science - November 5, 2020](https://www.nationalacademies.org/our-work/roundtable-on-aligning-incentives-for-open-science) 

[**Operationalizing better science in less time** - Integrating Open Science Tools into National Estuaries Programs Workflows Workshop - October 29, 2020](https://docs.google.com/presentation/d/1OHe4C2B9cGnT9niSguXwsWiK0M2sDsdeNjTOLWAgBX4/edit?usp=sharing)


[**Entryways to open data science and the power of welcome** — Keynote at the Earth Science Information Partners annual conference – *July 16, 2020 (remote)*](https://esip.figshare.com/articles/Entryways_to_open_data_science_and_the_power_of_welcome/12654689/1)

[**R and teamwork for better science in less time** — German Centre for Integrative Biodiversity Research (iDiv), Leipzig, Germany. *April 21, 2020 (remote)*](https://openscapes.github.io/slides/betterscience/idiv#1) 

[**Supercharging research with open data science and teamwork** — Keynote at Open Science Conference, Berlin, Germany *March 11, 2020 (remote)*](https://docs.google.com/presentation/d/16XtypOVGzuc50gYYsuUIhEkJubPdQztOYHmx9ObEiXg/edit?usp=sharing)

[**R and teamwork for better science in less time** — UMass Dartmouth's School for Marine Science & Technology (SMAST), New Bedford, Massachusetts *February 25, 2020*](https://openscapes.github.io/slides/betterscience/smast#1)

[**R and teamwork for better science in less time** — Southern California Coastal Water Research Project (SCCWRP), Costa Mesa, California *February 7, 2020*](https://openscapes.github.io/slides/betterscience/sccwrp#1) [(video)](https://vimeo.com/390086585)

[**R for Excel Users** — Workshop at RStudio::conf(2020), San Francisco, California *2020-01-27*](https://rstudio-conf-2020.github.io/r-for-excel/)

[**R for better science in less time** — headline talk at Southern California R Users All Hands Meetup, Los Angeles, California *2019-11-23*](https://openscapes.github.io/slides/betterscience/socalR#1)

[**R for better science in less time: Lessons from the Ocean Health Index and Openscapes** - invited talk at the School of Aquatic and Fisheries Sciences, University of Washington, Seattle, Washington *2019-11-21*](https://docs.google.com/presentation/d/1LA4EcnRxD11rjwbRh0hrjPG5J0dmiiuCbNaoQrz0XHU/edit?usp=sharing)

[**R and friends for better science in less time in big (and small) team collaborations** - invited talk at the eScience Institute, Seattle, Washington *2019-11-19*](https://openscapes.github.io/slides/betterscience/escience#1)

[**Building communities of practice around environmental open data science** - talk at FORCE11 Conference, Edinburgh, Scotland *2019-10-16*](https://zenodo.org/record/3497306#.Xbs3WSV7nOQ))

[**Better science in less time: Lessons from the Ocean Health Index and Openscapes** - invited talk at the Tampa Bay Estuary Program Open Science Workshop, St Petersburg, Florida (remote) *2019-09-05*](https://docs.google.com/presentation/d/13JkwCiXjfZfNucAsDwHI6FdEvpOngCv50cjnT7HXJK8/edit?usp=sharing) 

[**R for better science in less time** — opening keynote talk at useR! conference, Toulouse, France *2019-07-10*](https://jules32.github.io/useR-2019-keynote/#1) [(video, starts ~46:30)](https://www.youtube.com/watch?v=Z8PqwFPqn6Y)

[**Building communities of practice around environmental open data science** ](https://docs.google.com/presentation/d/1KXzPId1IvspsemIOmOUQEOqt8-Nw4Lhb2-Xvi_XZWeU/edit?usp=sharing) [— talk at csv,conf,v4 in Portland, Oregon *2019-05-08*](https://csvconf.com/) [(slides on Zenodo)](https://zenodo.org/record/2695625#.XN2CsKZ7nOQ)

[**How the Ocean Health Index enables better science in less time** — invited seminar at the Bren School of Environmental Science and Management, University of California at Santa Barbara *2019-04-15*](https://docs.google.com/presentation/d/1vqUJpdfjEzFzlh-cAPcIpUBwhFsaMSqyjDhQUjh6aR8/edit?usp=sharing)  

[**Streamlined workflows in R** — talk at RLadies Santa Barbara *2019-03-14*](https://jules32.github.io/streamlined-workflows/#1)  

[**Transforming how we approach marine science for management** — invited guest lecture at University of California at Santa Barbara Conservation Ecology course *2019-03-07*](https://docs.google.com/presentation/d/1UKo4kb6FOkZDqdDaMXN_jAVKkkYNs7BMiInMbXUJ_48/edit?usp=sharing) 

[**Building communities of practice around environmental open data science** — invited talk at the Palo Alto University Rotary Club Meeting *2019-02-08*](https://docs.google.com/presentation/d/1LwHpLQvIVeDoTNlZfrzpiYTifY4P9rGuqVq9TS9iFPI/edit?usp=sharing) 

[**My Fellowship with Mozilla: Building communities of practice around environmental open data science** — seminar at the National Center for Ecological Analysis and Synthesis *2018-11-07*](https://docs.google.com/presentation/d/1s6o4lqrn3zk2_UF2W-6A5orAT-bXREJ_mB6ghf-3eZQ/edit?usp=sharing)  

[**The power of open science: experience from the Ocean Health Index** — invited seminar at the Woods Hole Oceanographic Institution *2018-10-24*](https://docs.google.com/presentation/d/1SHvJbBWrGVqzjAPos1jbtxSn_2DAl44JmDgY5v2NxC8/edit?usp=sharing)  

[**Software Carpentry** — 2-day workshop at the Woods Hole Oceanographic Institution (WHOI) *2018-10-22*](https://jules32.github.io/2018-10-22-whoi/overview) [(Intro to data science book)](http://ohi-science.org/data-science-training)

[**What is the Ocean Health Index Toolbox and how can it help you?** — invited webinar at the Helmholz Open Science Institute *2018-07-12*](https://docs.google.com/presentation/d/1WKzbvF-XQl3lGzEc44fp8azssod9BcY2wMaAO0ZhFmk/edit?usp=sharing)  

[**The power of open science: experience from the Ocean Health Index** — invited seminar at the National University of Samoa *2018-05-22*](https://docs.google.com/presentation/d/14TteMSsHbzcEXG9zs9_mAOv0ivURTeJd7PewkSVqX2M/edit?usp=sharing)  

[**The power of open science: experience from the Ocean Health Index** — invited seminar at Moss Landing Marine Laboratories, California, USA *2018-04-05*](https://docs.google.com/presentation/d/1frhNFr-Lf5KZCzJtYMRSim2-iZ72zAJZ__0YrqAdbs8/edit?usp=sharing)

[**Data integration and team science** — 4 day workshop at NCEAS, California, USA *2018-03-12*](https://nceas.github.io/crescynt-training/data-integration)

[**The power of open science: experience from the Ocean Health Index**  —  invited keynote talk at the Royal Belgian Institute of Natural Sciences, Brussels *2018-02-27*](https://docs.google.com/presentation/d/10KkXEv4r3wWtdKvB6RFOPe809eMNldODaRqQxn-jeME/edit?usp=sharing)

[**Better science in less time using open data science tools**  —  invited seminar at Cal State University Monterey Bay *2017-12-04*](https://docs.google.com/presentation/d/1CVK8HRDubFU4UEduBK5q6JJebhbyVjB6SpTpjZI6q6Y/edit?usp=sharing)

[**Software Carpentry** — 2-day workshop at the Monterey Bay Aquarium Research Institute (MBARI) *2017-11-30*](https://jules32.github.io/2017-11-30-MBARI/overview) [(Intro to data science book)](http://ohi-science.org/data-science-training)

[**Reproducible Research: Better science in less time**  —  invited webinar for DataONE *2017-10-10*](https://docs.google.com/presentation/d/141gf6dIkQsOXJ74xWEeMFYOQEL41lZydywRRf_4RBPE/edit)

[**Better science in less time using data science tools: How open data science tools have improved our science**  —  invited talk at Cal Poly *2017-09-29*](https://docs.google.com/presentation/d/1IkxMgJwtJ17n51ENGudmL9rRmhgh3njGB0ivrracZIg/edit?usp=sharing)

[**Data Carpentry: Open and Reproducible Ecology** — 2-day workshop at the University of California Merced *2017-08-17*](https://snacktavish.github.io/2017-08-17-Yosemite/overview/) 

[**Better science in less time**  —  website to accompany our *Nature Ecology & Evolution* publication  *2017-05-23*](http://ohi-science.org/betterscienceinlesstime/) 

[**Better science in less time — open data science for marine science and management**  — talk at NCEAS Roundtable *2017-05-24* \[]()[**video**\]](https://www.youtube.com/watch?v=x4uzVAZvFCA)  

[**Transforming how we approach marine science for management**  — talk at EBM Tools Network Webinar *2017-05-02*](https://docs.google.com/presentation/d/1KDwUPVI12ioYzkhzzhnUEZbFJObuDzHPPSaOaN77Ye8/edit?usp=sharing) [\[]()[**video**\]](https://www.openchannels.org/webinars/2017/using-ocean-health-index-integrated-tool-implementing-ebm-and-coastal-management)

[**Making free websites with RStudio’s R Markdown**  —  tutorial at NCEAS *2016-12-14*](https://jules32.github.io/rmarkdown-website-tutorial/) 

[**Better science in less time using data science tools**  —  talk at WSN Conference *2016-11-15*](https://jules32.github.io/opensci-talk/short#1)

[**Being a marine data scientist**  —  invited talk at Stanford's Hopkins Marine Station *2016-10-21*](https://jules32.github.io/opensci-talk/#1) [\[]()[**video**\]](http://seawater.stanford.edu/Lowndes.mp4)

[**Resources for R and Data Science**  —  blog *2016-09-29*](http://ohi-science.org/news/Resources-for-R-and-Data-Science)  

[**Software Carpentry: Reproducible Science with RStudio and GitHub**  —  2-day workshop at Oxford University *2016-07-12*](http://jules32.github.io/2016-07-12-Oxford/overview/)

[**Software Carpentry**  —  2-day workshop at UC Santa Barbara *2016-04-15*](http://remi-daigle.github.io/2016-04-15-UCSB/overview/)

[**"Open science" and why it matters**  —  blog *2016-04-03*](http://jules32.github.io/resources/open-science/) 

[**Introduction to RStudio Awesomeness**  —  blog *2016-02-14*](http://jules32.github.io/resources/RStudio_intro/)

[**The Ocean Health Index and Shiny**  —  talk at RStudio's Shiny Conference *2016-01-30* ](http://ohi-science.org/ohimanual/tutorials/ohi_shiny/#1)
[\[]()[**video**\]](https://www.rstudio.com/resources/videos/ocean-health-index-analysis-with-shiny/)
[\[]()[**blog**\]](http://ohi-science.org/news/presentation-at-rstudio-shiny-conference)



# Publications

[***Google Scholar***](https://scholar.google.com/citations?user=qr9gICIAAAAJ&hl=en&authuser=1)

- [**JS Stewart Lowndes 2019**. *Scientific American*. Open software means kinder science.](https://blogs.scientificamerican.com/observations/open-software-means-kinder-science/)

- [**JS Stewart Lowndes et al. 2019**. *Nature Career Column*. Supercharge your research: a ten-week plan for open data science.](https://www.nature.com/articles/d41586-019-03335-4)

- [**BS Halpern et al. 2019**, *Scientific Reports*. Recent pace of change in human impact on the world’s ocean.](https://www.nature.com/articles/s41598-019-47201-9) 

- [**MJ Burgass et al. 2018**, *Regional Environmental Change*. A pan-Arctic assessment of the status of marine social-ecological systems.](https://link.springer.com/article/10.1007/s10113-018-1395-6)

- [**JS Stewart Lowndes et al. 2017**. *Nature Ecology & Evolution*. Our path to better science in less time using open data science tools.](https://www.nature.com/articles/s41559-017-0160)

    - [Nature article by Jeffrey Perkel: My digital toolbox: Julia Stewart Lowndes](http://blogs.nature.com/naturejobs/2017/05/23/techblog-julia-stewart-lowndes/)

- [**BS Halpern et al. 2017**, *PLOS ONE*. Drivers and implications of change in global ocean health over the past 5 years.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0178267) 

- [**RM Daigle et al. 2017**, *PLOS ONE*. Incorporating public priorities in the Ocean Health Index: Canada as a case study.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0178044) 
    
- [**SK Katona et al. 2017**. *OpenChannels*. Navigating the seascape of ocean management: waypoints on the voyage toward sustainable use.](https://www.openchannels.org/literature/16817)

- [**BS Halpern et al. 2016**, Chapter 7.8: Ocean Health Index for the world’s large marine ecosystems. In: IOC-UNESCO and UNEP. Large Marine Ecosystems: Status and Trends. United Nations Environment Programme, Nairobi, pp. 239–249.](http://www.geftwap.org/publications/lmes-technical-report/view)

- [**A Borja et al. 2016**, *Frontiers in Marine Science*. Overview of Integrative Assessment of Marine Systems: The Ecosystem Approach in Practice.](http://dx.doi.org/10.3389/fmars.2016.00020)

- [**JS Stewart Lowndes et al. 2015**, *PeerJ*. Best practices for assessing ocean health in multiple contexts using tailorable frameworks.](https://doi.org/10.7717/peerj.1503)

- [**BS Halpern et al. 2015**, *Nature communications*. Spatial and temporal changes in cumulative human impacts on the world's ocean.](http://www.nature.com/ncomms/2015/150714/ncomms8615/full/ncomms8615.html?message-global=remove&WT.ec_id=NCOMMS-20150715&spMailingID=49102925&spUserID=ODkwMTM2NjQyNgS2&spJobID=721894001&spReportId=NzIxODk0MDAxS0)

- [**BS Halpern et al. 2015**, *PloS One*. Patterns and emerging trends in global ocean health.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0117863) 

- [**JS Stewart et al. 2014**, *Global Change Biology*. Combined climate- and prey-mediated range expansion of Humboldt squid (*Dosidicus gigas*), a large marine predator in the California Current System.](http://onlinelibrary.wiley.com/doi/10.1111/gcb.12502/abstract) 

- [**R Rosa et al. 2013**, *Nova Science Publishers.* Advances in Squid Biology, Ecology and Fisheries.](https://books.google.com/books?id=ybKknQEACAAJ&dq=Advances+in+Squid+Biology,+Ecology+and+Fisheries+Nova+publishers&hl=en&sa=X&ved=0ahUKEwjCjc2VofPLAhXCsIMKHTN7CKYQ6AEIHTAA)

- [**JS Stewart et al. 2013**, *Deep Sea Research II*. Behavioral ecology of Jumbo squid (*Dosidicus gigas*): in relation to oxygen minimum zones.](http://www.sciencedirect.com/science/article/pii/S0967064512000860) 

    - [BBC news article and radio interview by Jonathan Amos: Humboldt squid’s impressive dives](http://www.bbc.com/news/science-environment-17117200)

- [**JS Stewart et al. 2013**, *Deep Sea Research II* Onshore-offshore movement of jumbo squid (Dosidicus gigas) on the continental shelf.](http://www.sciencedirect.com/science/article/pii/S0967064512001592) 

- [**RK O’Dor et al. 2013**, *Deep Sea Research II*. Squid rocket science: how squid launch into air.](http://www.sciencedirect.com/science/article/pii/S0967064512000884)

    - [Nature News article by Jessica Marshall: Squid can fly to save energy](http://www.nature.com/news/squid-can-fly-to-save-energy-1.10060)

- [**JC Field et al. 2013**, *Deep Sea Research II*. Foraging ecology and movement patterns of the Humboldt squid in the California Current.](http://www.sciencedirect.com/science/article/pii/S0967064512001713)

- [**JS Stewart et al. 2012**. *Marine Ecology Progress Series* Marine predator migration during range expansion: Humboldt squid (*Dosidicus gigas*) in the California Current System.](http://www.int-res.com/abstracts/meps/v471/p135-150/)

- [**JS Stewart, 2012**. PhD Dissertation, Stanford University. Humboldt squid in the northern California Current System.](https://purl.stanford.edu/pb685tk3754) 

    - [New Scientist article with accompanying video by Peter Aldhous: Doing battle with the red devils of the Pacific](http://www.sciencedirect.com/science/article/pii/S0262407910600243)
    
- [**WF Gilly et al. 2012**, *Journal of Experimental Biology*. Locomotion and behavior of Humboldt squid, *Dosidicus gigas*, in relation to natural hypoxia in the Gulf of California, Mexico.](http://jeb.biologists.org/content/215/18/3175.short)

- [**AC Iles et al. 2012**, *Global Change Biology*.Climate driven trends and ecological implications of event-scale upwelling in the California Current System.](http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2011.02567.x/abstract;jsessionid=5A5A881CBF90CDB4245F3C08AE441DD6.f03t03?deniedAccessCustomisedMessage=&userIsAuthenticated=false)

- [**CB Woodson et al. 2011**, *Geophysical Research Letters*. Observations of internal wave packets propagating along-shelf in northern Monterey Bay.](http://onlinelibrary.wiley.com/doi/10.1029/2010GL045453/abstract?deniedAccessCustomisedMessage=&userIsAuthenticated=false).

- [**RK O'Dor et al. 2007**. GLOBEC Report No. 24. Fin Flaps: key adaptation for habitat expansion in the squid, Dosidicus gigas?](http://www.globec.org/index.php?act=downloads&view=item&did=80)

- [**JS Stewart and WF Gilly. 2005**, *Biological Bulletin*. Piscivorous behavior of a temperate cone snail, *Conus californicus*.](http://www.biolbull.org/content/209/2/146.short)

    - [Editor’s Pick and cover article](http://www.biolbull.org/content/209/2.cover-expansion)


# Media about my work

- [**Tech tools to make research more open and inclusive**, 2020. Kendall Powell, *Nature*](https://www.nature.com/articles/d41586-020-00216-z)

- [**The coupling of innovation and open data science tools for science has been fascinating to me and hard to tease apart: An interview with Dr Julia Stewart Lowndes**, 2020. Alison Oliver, *Statistics Views*](https://www.statisticsviews.com/details/feature/11216365/The-coupling-of-innovation-and-open-data-science-tools-for-science-has-been-fasc.html)

- [**Open Science and 'Star Wars'**, 2019. Mozilla, *Medium*](https://medium.com/read-write-participate/open-science-and-star-wars-2577b8081e8f)

- [**A Rising Tide: Funding Ocean Science**, 2019. Science Philanthropy Alliance, *Alliance blog post*.](https://www.sciencephilanthropyalliance.org/a-rising-tide-funding-ocean-science-alliance-blog-post/)

- [**Julie Lowndes Wants the Force of Open Data Science to Be with You**, 2019. *NCEAS Portrait*](https://www.nceas.ucsb.edu/news/nceas-portrait-julie-lowndes)

<!--- https://sbseasons.com/2019/02/women-in-science-photo-exhibition-at-moxi/ --->

- [**Announcing Openscapes: Open Science is Better Science**, 2019. Mozilla, *Medium*](https://medium.com/read-write-participate/announcing-openscapes-open-science-is-better-science-debe520d3de5)

- [**Mozilla announces 25 new fellows in openness, science, and tech policy**, 2018. Mozilla, *Medium*](https://blog.mozilla.org/blog/2018/08/21/mozilla-announces-25-new-fellows-in-openness-science-and-tech-policy/)

- [**A toolkit for data transparency takes shape**, 2018. Jeffrey Perkel, *Nature*](https://www.nature.com/articles/d41586-018-05990-5)

- [**.rprofile: Julia Stewart Lowndes**, 2018. Sean Kross & Kelly O’Briant, *rOpenSci blog*](https://ropensci.org/blog/2018/02/09/rprofile-julia-stewart-lowndes/)

- [**My digital toolbox: Julia Stewart Lowndes**, 2017. Jeffrey Perkel, *Nature* ](http://blogs.nature.com/naturejobs/2017/05/23/techblog-julia-stewart-lowndes/)  

- [**The Common Language of Conservation**, 2017. Michelle Nijhuis, *The Last Word On Nothing*](http://www.lastwordonnothing.com/2017/05/24/the-common-language-of-conservation/)

- [**Awash in Sea of Data, Ecologists Turn to Open Access Tools**, 2017. John Rennie, *Quanta Magazine*](https://www.quantamagazine.org/awash-in-sea-of-data-ecologists-turn-to-open-access-tools-20170524/)

- [**Ecologists Are Drowning in Sea of Data. These Tools Could Help**, 2017. John Rennie, *WIRED*](https://www.wired.com/2017/05/ecologists-drowning-sea-data-open-access-tools-help)

- [**Magical morphing jumbo squid are taking over the eastern Pacific**, 2015. Michael Tennesen, *New Scientist*](https://www.newscientist.com/article/mg22730380-600-magical-morphing-jumbo-squid-are-taking-over-the-eastern-pacific/?utm_source=NSNS&utm_medium=SOC&utm_campaign=hoot&cmpid=SOC%7CNSNS%7C2015-GLOBAL-hoot) 

- [**Baja nota para la salud de los océanos**, 2014. Aleszu Bajak, *SciDevNet*](http://www.scidev.net/america-latina/conservacion/noticias/baja-nota-para-la-salud-de-los-oceanos.html)

- [**The ten best ocean stories of 2012: year of the squid**, 2012. *Smithsonian Magazine* ](http://www.smithsonianmag.com/ist/?next=/science/2012/12/the-ten-best-ocean-stories-of-2012)

- [**Humboldt squid’s impressive dives**, 2012. Jonathan Amos, *BBC*](http://www.bbc.com/news/science-environment-17117200)

- [**Squid can fly to save energy**, 2012. Jessica Marshall, *Nature News*](http://www.nature.com/news/squid-can-fly-to-save-energy-1.10060) 

- [**Laid-back squid slow down with oxygen levels drop**, 2012. Yfke Hager, *PNAS*](http://jeb.biologists.org/content/215/18/ii) 

- [**Hunt for the Giant Squid**, 2011. *National Geographic and Ammonite*](http://www.ammonite.co.uk/news/hunt-for-the-giant-squid/)

- [**Kraken**, 2011. Wendy Williams, *Abrams Image publishers*](http://www.abramsbooks.com/product/kraken_9780810984653/) 

- [**Alien Squid Invasion**, 2011. *National Geographic Channel Wild Case Files*](http://natgeotv.com/za/wild-case-files/videos/cannibal-squid-invasion) 

- [**Doing Battle with the Red Devils of the Pacific**, 2011. Peter Aldhous, *New Scientist*](http://www.sciencedirect.com/science/article/pii/S0262407910600243) 

- [**Graduate students take urban runoff by storm**, Center for Ocean Solutions blog, 2011]()

- [**What happened to the Humboldt squid?** 2010. Jennifer Skene, *KQED Quest*](http://ww2.kqed.org/quest/2010/08/09/what-happened-to-the-humboldt-squid-2/) 

- [**Squids-4-Kids in Washington DC**, 2010. Lou Bergeron, *Stanford News*](http://news.stanford.edu/news/2010/october/squids-for-kids-102210.html) 

- [**Squids-4-Kids**, 2010. *Stanford Daily*](http://www.stanforddaily.com/2010/11/08/squids-for-kids-brings-cephalopods-to-the-classroom/)

